# Generated by Django 5.2.8 on 2025-11-29 08:18

import django.db.models.deletion
import product.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_start_date', models.DateField()),
                ('number_of_payments', models.PositiveIntegerField()),
                ('periodicity', product.fields.PeriodicityField(max_length=5)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.credit')),
            ],
        ),
    ]
